### ISSUE TITLE
Special keys not working

### ISSUE THREAD

**Issue by scifiaholic** [Mystfit/ESP32-BLE-CompositeHID#13]
all the letters work for me, however the keyboard library doesn't seem to do anything when I use it to send KEY_RIGHTALT, KEY_RIGHTMETA, KEY_RIGHTCTRL, or KEY_ESC. Nothing happens on my PC attached over bluetooth to the ESP32. I have another library, listed below, that works fine, but doesn't have your callbacks with the CAPS_LOCK and other keys when a different keyboard sets their status. I would really like to use your library! 

https://github.com/blackketter/ESP32-BLE-Combo

**Comment by Mystfit** [comment]
Hi, thanks for the feedback!

I've updated the [PressKey](https://github.com/Mystfit/ESP32-BLE-CompositeHID/blob/master/examples/KeyboardExamples/PressKey/PressKey.ino) example with some examples for how to interact with the modifier keys. 

Specifically, you want to use `modifierKeyPress `and `modifierKeyRelease`.

Can you let me know if this solves your problem? If so then I'll mark this as completed.
