### ISSUE TITLE
How do I program a mouse click?

### ISSUE THREAD

**Issue by Knockoi** [Mystfit/ESP32-BLE-CompositeHID#4]
I want to control the mouser pointer with the joystick, but I don't know how to give the command to click the left button?

**Comment by Knockoi** [comment]
mouse->press(MOUSE_LEFT);
 mouse->release(MOUSE_LEFT);

**Comment by Mystfit** [comment]
Apologies, seems as though I forgot to include an example for mouse presses.

The function is `mouse->mousePress(MOUSE_BUTTON)` or `mouse->mouseRelease(MOUSE_BUTTON)` where `MOUSE_BUTTON` is one of:

- MOUSE_LOGICAL_LEFT_BUTTON
- MOUSE_LOGICAL_RIGHT_BUTTON
- MOUSE_LOGICAL_BUTTON_3
- MOUSE_LOGICAL_BUTTON_4
- MOUSE_LOGICAL_BUTTON_5

For example, the following will press the left mouse button for 100ms then release it.

```
mouse->mousePress(MOUSE_LOGICAL_LEFT_BUTTON);
mouse->sendMouseReport();
delay(100);
mouse->mouseRelease(MOUSE_LOGICAL_LEFT_BUTTON);
mouse->sendMouseReport();

```

**Comment by Knockoi** [comment]
Thank you very much!!! 
For the example you provided, what about the Keyboard example? I want to press the left arrow and the right arrow, how do I write it?
How can I check it in the future?
